name: streamlit
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - tk
  - pip
  - pandas
  - matplotlib
  - seaborn
  - folium
  - netcdf4
  - xarray
  - jupyter-server-proxy
  - nbserverproxy
  - pip:
    - streamlit==0.53.0