name: streamlit
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pandas
  - matplotlib==3.1.*
  - seaborn
  - folium
  - netcdf4
  - xarray
  - jupyter-server-proxy
  - nbserverproxy
  - pip:
    - streamlit
    - streamlit-folium
